<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signUp/register"); ?>

    <p>
        <label for="nama">Name</label>
        <?php echo $this->tag->textField("nama"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <label for="pass">Password</label>
        <?php echo $this->tag->textField("pass"); ?>
    </p>

    <p>
        <label for="alamat">Alamat</label>
        <?php echo $this->tag->textField("alamat"); ?>
    </p>

    <p>
        <label for="no_hp">Nomor Hp</label>
        <?php echo $this->tag->textField("no_hp"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>