<table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th colspan="3" align="center"><h1 align="center">Menu</h1></th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["listUsers", "View All Users", 'class' => 'btn btn-primary']); ?></h3></th>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["editProduk", "Edit Produk", 'class' => 'btn btn-primary']); ?></h3></th>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["nambahProduk", "Tambah Produk", 'class' => 'btn btn-primary']); ?></h3></th>
        </tr>
        <tr>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["hapusProduk", "Hapus Produk", 'class' => 'btn btn-primary']); ?></h3></th>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["listProduk", "List Produk", 'class' => 'btn btn-primary']); ?></h3></th>
            <th><h3 align="center"><?php echo $this->tag->linkTo(["cariProduk", "Cari Produk", 'class' => 'btn btn-primary']); ?></h3></th>
        </tr>
        </tbody>
</table>
